### ISSUE TITLE
为什么Windows下dtunnel经常闪退

### ISSUE THREAD

**Issue by Kwan9** [vzex/dog-tunnel#109]
请问如何解决？

**Comment by joostshao** [comment]
Linux下贴代码喽
version 1.32 udp  lite version
OS： debian 9
```
internal/poll.runtime_pollWait(0x7f43f3b56700, 0x72, 0x0)
	D:/Go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42021e398, 0x72, 0xffffffffffffff00, 0x7f5e00, 0x7f3180)
	D:/Go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42021e398, 0xc42008ea00, 0x1388, 0x1388)
	D:/Go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42021e380, 0xc42008ea00, 0x1388, 0x1388, 0x0, 0x0, 0x0)
	D:/Go/src/internal/poll/fd_unix.go:125 +0x17b
net.(*netFD).Read(0xc42021e380, 0xc42008ea00, 0x1388, 0x1388, 0x3, 0xc420445680, 0xc4200589c0)
	D:/Go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420204108, 0xc42008ea00, 0x1388, 0x1388, 0x0, 0x0, 0x0)
	D:/Go/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc4201c1ef0, 0xc42008ea00, 0x1388, 0x1388, 0xc42008ea00, 0x500, 0x1388)
	D:/Go/src/bufio/bufio.go:199 +0x1a3
main.(*clientSession).handleLocalServerResponse(0xc42000e780, 0xc4200b8580, 0x400)
	D:/gopath/src/github.com/vzex/dog-tunnel/client.go:2120 +0x426
created by main.(*Client).MultiListen.func2
	D:/gopath/src/github.com/vzex/dog-tunnel/client.go:1715 +0x22b

goroutine 713161 [IO wait]:
internal/poll.runtime_pollWait(0x7f43f3d9a1f0, 0x72, 0x0)
	D:/Go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42021e718, 0x72, 0xffffffffffffff00, 0x7f5e00, 0x7f3180)
	D:/Go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42021e718, 0xc4204bea00, 0x1388, 0x1388)
	D:/Go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42021e700, 0xc4204bea00, 0x1388, 0x1388, 0x0, 0x0, 0x0)
	D:/Go/src/internal/poll/fd_unix.go:125 +0x17b
net.(*netFD).Read(0xc42021e700, 0xc4204bea00, 0x1388, 0x1388, 0x3, 0xc4201aef00, 0xc4202738c0)
	D:/Go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4201d4120, 0xc4204bea00, 0x1388, 0x1388, 0x0, 0x0, 0x0)
	D:/Go/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc4204d9ef0, 0xc4204bea00, 0x1388, 0x1388, 0xc4204bea00, 0x2e, 0x1388)
	D:/Go/src/bufio/bufio.go:199 +0x1a3
main.(*clientSession).handleLocalServerResponse(0xc42000ee10, 0xc4200b8580, 0x418)
	D:/gopath/src/github.com/vzex/dog-tunnel/client.go:2120 +0x426
created by main.(*Client).MultiListen.func2
	D:/gopath/src/github.com/vzex/dog-tunnel/client.go:1715 +0x22b

goroutine 714234 [IO wait]:
internal/poll.runtime_pollWait(0x7f43f3d9a2b0, 0x72, 0x0)
	D:/Go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420102798, 0x72, 0xffffffffffffff00, 0x7f5e00, 0x7f3180)
	D:/Go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420102798, 0xc4204a7500, 0x1388, 0x1388)
	D:/Go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420102780, 0xc4204a7500, 0x1388, 0x1388, 0x0, 0x0, 0x0)
	D:/Go/src/internal/poll/fd_unix.go:125 +0x17b
net.(*netFD).Read(0xc420102780, 0xc4204a7500, 0x1388, 0x1388, 0x3, 0xc42029c900, 0xc4201fe000)
	D:/Go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000c1f0, 0xc4204a7500, 0x1388, 0x1388, 0x0, 0x0, 0x0)
	D:/Go/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc4203d7ef0, 0xc4204a7500, 0x1388, 0x1388, 0xc4204a7500, 0x2e, 0x1388)
	D:/Go/src/bufio/bufio.go:199 +0x1a3
main.(*clientSession).handleLocalServerResponse(0xc4204f6870, 0xc4200b8580, 0x420)
	D:/gopath/src/github.com/vzex/dog-tunnel/client.go:2120 +0x426
created by main.(*Client).MultiListen.func2
	D:/gopath/src/github.com/vzex/dog-tunnel/client.go:1715 +0x22b
```

**Comment by vzex** [comment]
@joostshao 你的栈看起来已经跑了70多w个go线程，我能问下你的使用环境吗，是在做压力测试？

**Comment by joostshao** [comment]
没有，就普通的使用环境，
linux下的时常奔溃，windows的没问题 
-v -action socks5 -encrypt -xor 1213343 -local :8888 -pipe 5 -session_timeout 60

**Comment by doc-hub** [comment]
@joostshao  可能是session_timeout参数的问题，去掉就OK了，看 #123，错误信息和描述相似

**Comment by pedxyuyuko** [comment]
> @joostshao 可能是session_timeout参数的问题，去掉就OK了，看 #123，错误信息和描述相似

如去掉 session_timeout 参数会导致无法运行
![image](https://user-images.githubusercontent.com/39913604/61166912-b1d1a880-a568-11e9-832a-1761b77183d1.png)
