### ISSUE TITLE
session_timeout致错

### ISSUE THREAD

**Issue by void285** [vzex/dog-tunnel#123]
release下载的1.4.1的dtunnel_lite windows版，若启用session_timeout，一段时间（几分钟或十几分钟，应该是跟请求量有关）后会报错退出，100%重现。

错误信息：
```
goroutine 20633 [IO wait]:
internal/poll.runtime_pollWait(0x2f54770, 0x72, 0x758880)
        d:/go/src/runtime/netpoll.go:173 +0x6d
internal/poll.(*pollDesc).wait(0xc0001237c8, 0x72, 0x635100, 0x0, 0x0)
        d:/go/src/internal/poll/fd_poll_runtime.go:85 +0xa1
internal/poll.(*ioSrv).ExecIO(0x8d61a8, 0xc000123618, 0x725e88, 0xc00027cf60, 0x5b, 0x5b)
        d:/go/src/internal/poll/fd_windows.go:222 +0x137
internal/poll.(*FD).Read(0xc000123600, 0xc00060aa00, 0x1388, 0x1388, 0x0, 0x0, 0x0)
        d:/go/src/internal/poll/fd_windows.go:487 +0x252
net.(*netFD).Read(0xc000123600, 0xc00060aa00, 0x1388, 0x1388, 0x75a0e0, 0x40, 0xc000593cf0)
        d:/go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc000006060, 0xc00060aa00, 0x1388, 0x1388, 0x0, 0x0, 0x0)
        d:/go/src/net/net.go:177 +0x6f
bufio.(*Reader).Read(0xc000593ef0, 0xc00060aa00, 0x1388, 0x1388, 0xc00060aa00, 0x41, 0x1388)
        d:/go/src/bufio/bufio.go:202 +0x12e
main.(*clientSession).handleLocalServerResponse(0xc000294640, 0xc0000b0420, 0xdd)
        D:/gopath/src/github.com/vzex/dog-tunnel/client.go:2392 +0x361
created by main.(*Client).MultiListen.func2
        D:/gopath/src/github.com/vzex/dog-tunnel/client.go:1948 +0x211
```

**Comment by pedxyuyuko** [comment]
我也是这个问题  不知道可不可以通过回退版本来解决 或许可以调高session_timeout来解决(?)

**Comment by Leadrive** [comment]
这里面有个隐藏的bug
