### ISSUE TITLE
[bug]反馈，局域网两台机器崩溃问题

### ISSUE THREAD

**Issue by xsjqqq123** [vzex/dog-tunnel#92]
我将程序（link端）弄到了android上跑起来后，android在4G或别人路由器的WIFI下工作正常，而用自己的路由器时（reg与link在同一局域网），reg端崩溃（用的是官网下载下来的），同一局域网下的电脑上运行link，reg却没问题。。
错误日志如下：

panic: runtime error: index out of range

goroutine 14 [running]:
github.com/vzex/dog-tunnel/nat/stun.BindResponse(0xc42001d364, 0xc, 0xc, 0xc420015ad0, 0x0, 0x0, 0x0, 0x0, 0xc420046e90, 0x28, ...)
        d:/goget/src/github.com/vzex/dog-tunnel/nat/stun/stun.go:149 +0x41e
github.com/vzex/dog-tunnel/nat.(*AttemptEngine).read(0xc420018750, 0xed0759a32, 0x22246ad8)
        d:/goget/src/github.com/vzex/dog-tunnel/nat/nat.go:199 +0x3e1
github.com/vzex/dog-tunnel/nat.(*AttemptEngine).run(0xc420018750, 0xc42013be78, 0x0, 0x0, 0xc420099520, 0x17, 0x0, 0x0)
        d:/goget/src/github.com/vzex/dog-tunnel/nat/nat.go:262 +0x1b8
github.com/vzex/dog-tunnel/nat.(*AttemptEngine).GetConn(0xc420018750, 0xc420045e78, 0x0, 0x0, 0x766580, 0x40e900, 0xc420015680, 0x30)
        d:/goget/src/github.com/vzex/dog-tunnel/nat/nat.go:85 +0x4d
main.(*UDPMakeSession).beginMakeHole(0xc42001cff0, 0x0, 0x0)
        D:/goget/src/github.com/vzex/dog-tunnel/client.go:285 +0xe40
created by main.handleResponse
        D:/goget/src/github.com/vzex/dog-tunnel/client.go:142 +0xdfe

**Comment by xsjqqq123** [comment]
另一个服务端崩溃的：
2017/04/06 04:59:36 OnLogin 1491425976
read tcp 115.126.52.156:8000->163.125.235.86:45498: use of closed network connection
panic: close of closed channel

goroutine 329 [running]:
panic(0x70c880, 0xc82000c7c0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.handleClient(0x7f015556c028, 0xc820259500)
        /home/xxx/gopath/src/github.com/vzex/dog-tunnel/server.go:46 +0x4b1
created by main.main.func1
        /home/xxx/gopath/src/github.com/vzex/dog-tunnel/server.go:435 +0x7b
root@cloud:~#
